### ISSUE TITLE
Blog is broken on clicking older posts.

### ISSUE THREAD

**Issue by gokul1794** [namshi/namshi.github.com#101]
![namshi-blog-broken](https://user-images.githubusercontent.com/6311809/37980939-65720e60-31fd-11e8-8910-9970c4ca5348.png)
Go to tech.namshi.io, scroll to the bottom and clicking older posts shows whats attached in the screenshot.

**Comment by joejean** [comment]
Thanks @gokul1794. We will fix it.

**Comment by shidhincr** [comment]
Issue is fixed
